### ISSUE TITLE
Configure lifecycle policy for intermediate output buckets.

### ISSUE THREAD

**Issue by sharkinsspatial** [NASA-IMPACT/hls-orchestration#271]
In UAH, we manually configured lifecycle policies for our [intermediate data output buckets](https://github.com/NASA-IMPACT/hls-orchestration/blob/dev/stack/stack.py#L168-L180) for forward processing.  Given that this is now a normalized process, this default lifecycle policy (2 months) should be included directly in the CDK code.

**Comment by sharkinsspatial** [comment]
@chuckwondo Can you also tackle this ticket when you are back in next week.

**Comment by chuckwondo** [comment]
Will do!
